//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowSongText.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShowSongText.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add selected.
        /// </summary>
        public static string AddSongToPlaylist_AddSelected {
            get {
                return ResourceManager.GetString("AddSongToPlaylist_AddSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose songs.
        /// </summary>
        public static string AddSongToPlaylist_Title {
            get {
                return ResourceManager.GetString("AddSongToPlaylist_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are sure you want to delete.
        /// </summary>
        public static string AlertDialog_AreYouSureToDelete {
            get {
                return ResourceManager.GetString("AlertDialog_AreYouSureToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string AlertDialog_Cancel {
            get {
                return ResourceManager.GetString("AlertDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the name again and try again..
        /// </summary>
        public static string AlertDialog_CheckNameAndTryAgain {
            get {
                return ResourceManager.GetString("AlertDialog_CheckNameAndTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete at least one field (author or title)..
        /// </summary>
        public static string AlertDialog_CompleteAtLeastOneField {
            get {
                return ResourceManager.GetString("AlertDialog_CompleteAtLeastOneField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find artist&apos;s songs:.
        /// </summary>
        public static string AlertDialog_CouldNotFindArtistsSongs {
            get {
                return ResourceManager.GetString("AlertDialog_CouldNotFindArtistsSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find matching artists.
        /// </summary>
        public static string AlertDialog_CouldntFindMachingArtists {
            get {
                return ResourceManager.GetString("AlertDialog_CouldntFindMachingArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name..
        /// </summary>
        public static string AlertDialog_EnterName {
            get {
                return ResourceManager.GetString("AlertDialog_EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter title and author..
        /// </summary>
        public static string AlertDialog_EnterNameAndTitle {
            get {
                return ResourceManager.GetString("AlertDialog_EnterNameAndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string AlertDialog_Error {
            get {
                return ResourceManager.GetString("AlertDialog_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are trying to move two or more songs, please move one at a time!.
        /// </summary>
        public static string AlertDialog_MoveMoreThanOneSong {
            get {
                return ResourceManager.GetString("AlertDialog_MoveMoreThanOneSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist name cannot be empty!.
        /// </summary>
        public static string AlertDialog_NameCannotBeEmpty {
            get {
                return ResourceManager.GetString("AlertDialog_NameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string AlertDialog_No {
            get {
                return ResourceManager.GetString("AlertDialog_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string AlertDialog_OK {
            get {
                return ResourceManager.GetString("AlertDialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist created!.
        /// </summary>
        public static string AlertDialog_PlaylistCreated {
            get {
                return ResourceManager.GetString("AlertDialog_PlaylistCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search problem!.
        /// </summary>
        public static string AlertDialog_SearchProblem {
            get {
                return ResourceManager.GetString("AlertDialog_SearchProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select artist and track manually..
        /// </summary>
        public static string AlertDialog_SelectArtistAndTrackManually {
            get {
                return ResourceManager.GetString("AlertDialog_SelectArtistAndTrackManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string AlertDialog_Success {
            get {
                return ResourceManager.GetString("AlertDialog_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text not found!.
        /// </summary>
        public static string AlertDialog_TextNotFound {
            get {
                return ResourceManager.GetString("AlertDialog_TextNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find track for:.
        /// </summary>
        public static string AlertDialog_TextNotFoundFor {
            get {
                return ResourceManager.GetString("AlertDialog_TextNotFoundFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many matching results, please refine your search!.
        /// </summary>
        public static string AlertDialog_ToManyMachingResults {
            get {
                return ResourceManager.GetString("AlertDialog_ToManyMachingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error.
        /// </summary>
        public static string AlertDIalog_UnexpectedError {
            get {
                return ResourceManager.GetString("AlertDIalog_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program encountered an unexpected error, please describe the situation in which it occurred and submit a report via the Report a problem option..
        /// </summary>
        public static string AlertDIalog_UnexpectedErrorMessage {
            get {
                return ResourceManager.GetString("AlertDIalog_UnexpectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string AlertDialog_Warning {
            get {
                return ResourceManager.GetString("AlertDialog_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string AlertDialog_Yes {
            get {
                return ResourceManager.GetString("AlertDialog_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection settings.
        /// </summary>
        public static string ConnectionSettings_Title {
            get {
                return ResourceManager.GetString("ConnectionSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string ConnectionSettingsClient_Connect {
            get {
                return ResourceManager.GetString("ConnectionSettingsClient_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to the server.
        /// </summary>
        public static string ConnectionSettingsClient_ConnectedToServer {
            get {
                return ResourceManager.GetString("ConnectionSettingsClient_ConnectedToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect the connection.
        /// </summary>
        public static string ConnectionSettingsClient_DisconnectConnection {
            get {
                return ResourceManager.GetString("ConnectionSettingsClient_DisconnectConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP:.
        /// </summary>
        public static string ConnectionSettingsClient_IP {
            get {
                return ResourceManager.GetString("ConnectionSettingsClient_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter the server&apos;s IP.
        /// </summary>
        public static string ConnectionSettingsClient_IPPlaceholder {
            get {
                return ResourceManager.GetString("ConnectionSettingsClient_IPPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string ConnectionSettingsClient_Port {
            get {
                return ResourceManager.GetString("ConnectionSettingsClient_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter the port number.
        /// </summary>
        public static string ConnectionSettingsClient_PortPlaceholder {
            get {
                return ResourceManager.GetString("ConnectionSettingsClient_PortPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run presentations.
        /// </summary>
        public static string ConnectionSettingsClient_RunPresentations {
            get {
                return ResourceManager.GetString("ConnectionSettingsClient_RunPresentations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string ConnectionSettingsHeaders_Client {
            get {
                return ResourceManager.GetString("ConnectionSettingsHeaders_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string ConnectionSettingsHeaders_Server {
            get {
                return ResourceManager.GetString("ConnectionSettingsHeaders_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected devices: .
        /// </summary>
        public static string ConnectionSettingsServer_ComnnectedDevices {
            get {
                return ResourceManager.GetString("ConnectionSettingsServer_ComnnectedDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP: .
        /// </summary>
        public static string ConnectionSettingsServer_IP {
            get {
                return ResourceManager.GetString("ConnectionSettingsServer_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port: .
        /// </summary>
        public static string ConnectionSettingsServer_Port {
            get {
                return ResourceManager.GetString("ConnectionSettingsServer_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is running.
        /// </summary>
        public static string ConnectionSettingsServer_ServerRunning {
            get {
                return ResourceManager.GetString("ConnectionSettingsServer_ServerRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the server.
        /// </summary>
        public static string ConnectionSettingsServer_StartServer {
            get {
                return ResourceManager.GetString("ConnectionSettingsServer_StartServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the server.
        /// </summary>
        public static string ConnectionSettingsServer_StopServer {
            get {
                return ResourceManager.GetString("ConnectionSettingsServer_StopServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty fields.
        /// </summary>
        public static string ConnectionSettingsVM_EmptyField {
            get {
                return ResourceManager.GetString("ConnectionSettingsVM_EmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the port number.
        /// </summary>
        public static string ConnectionSettingsVM_PortNumber {
            get {
                return ResourceManager.GetString("ConnectionSettingsVM_PortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a playlist name: .
        /// </summary>
        public static string DisplayEntry_EnterPlaylistName {
            get {
                return ResourceManager.GetString("DisplayEntry_EnterPlaylistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an artist:.
        /// </summary>
        public static string DisplayPositionToChoose_ChooseArtist {
            get {
                return ResourceManager.GetString("DisplayPositionToChoose_ChooseArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a song:.
        /// </summary>
        public static string DisplayPositionToChoose_ChooseSong {
            get {
                return ResourceManager.GetString("DisplayPositionToChoose_ChooseSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singer&apos;s assistant.
        /// </summary>
        public static string MainPage_ApplicationName {
            get {
                return ResourceManager.GetString("MainPage_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by Krzysztof Rutana.
        /// </summary>
        public static string MainPage_Author {
            get {
                return ResourceManager.GetString("MainPage_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string PlaylistDetail_Name {
            get {
                return ResourceManager.GetString("PlaylistDetail_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs:.
        /// </summary>
        public static string PlaylistDetail_Songs {
            get {
                return ResourceManager.GetString("PlaylistDetail_Songs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist details.
        /// </summary>
        public static string PlaylistDetail_Title {
            get {
                return ResourceManager.GetString("PlaylistDetail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string PlaylistList_Title {
            get {
                return ResourceManager.GetString("PlaylistList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send message.
        /// </summary>
        public static string RaportProblem_ButtonText {
            get {
                return ResourceManager.GetString("RaportProblem_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe the problem and send a message..
        /// </summary>
        public static string RaportProblem_DescribeProblem {
            get {
                return ResourceManager.GetString("RaportProblem_DescribeProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a problem with the app?.
        /// </summary>
        public static string RaportProblem_DoYouHaveProblem {
            get {
                return ResourceManager.GetString("RaportProblem_DoYouHaveProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject:.
        /// </summary>
        public static string RaportProblem_Subject {
            get {
                return ResourceManager.GetString("RaportProblem_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text:.
        /// </summary>
        public static string RaportProblem_Text {
            get {
                return ResourceManager.GetString("RaportProblem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a problem.
        /// </summary>
        public static string RaportProblem_Title {
            get {
                return ResourceManager.GetString("RaportProblem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database backup.
        /// </summary>
        public static string Settings_Backup {
            get {
                return ResourceManager.GetString("Settings_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create backup.
        /// </summary>
        public static string Settings_Backup_MakeBackupBtn {
            get {
                return ResourceManager.GetString("Settings_Backup_MakeBackupBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore backup.
        /// </summary>
        public static string Settings_Backup_RestoreBackupBtn {
            get {
                return ResourceManager.GetString("Settings_Backup_RestoreBackupBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chords above / to the right of the text:.
        /// </summary>
        public static string Settings_ChordsPosition {
            get {
                return ResourceManager.GetString("Settings_ChordsPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size:.
        /// </summary>
        public static string Settings_FontSize {
            get {
                return ResourceManager.GetString("Settings_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language:.
        /// </summary>
        public static string Settings_SelectLanguage {
            get {
                return ResourceManager.GetString("Settings_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show chords?.
        /// </summary>
        public static string Settings_ShowChords {
            get {
                return ResourceManager.GetString("Settings_ShowChords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add song.
        /// </summary>
        public static string SongAddAndDetail_AddSong {
            get {
                return ResourceManager.GetString("SongAddAndDetail_AddSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string SongAddAndDetail_Author {
            get {
                return ResourceManager.GetString("SongAddAndDetail_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add chords?.
        /// </summary>
        public static string SongAddAndDetail_Chords {
            get {
                return ResourceManager.GetString("SongAddAndDetail_Chords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste text.
        /// </summary>
        public static string SongAddAndDetail_PasteButton {
            get {
                return ResourceManager.GetString("SongAddAndDetail_PasteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists:.
        /// </summary>
        public static string SongAddAndDetail_Playlists {
            get {
                return ResourceManager.GetString("SongAddAndDetail_Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song details.
        /// </summary>
        public static string SongAddAndDetail_SongDetail {
            get {
                return ResourceManager.GetString("SongAddAndDetail_SongDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song key:.
        /// </summary>
        public static string SongAddAndDetail_SongKey {
            get {
                return ResourceManager.GetString("SongAddAndDetail_SongKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text:.
        /// </summary>
        public static string SongAddAndDetail_Text {
            get {
                return ResourceManager.GetString("SongAddAndDetail_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string SongAddAndDetail_TitleName {
            get {
                return ResourceManager.GetString("SongAddAndDetail_TitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a playlist.
        /// </summary>
        public static string SongList_CreatePlaylist {
            get {
                return ResourceManager.GetString("SongList_CreatePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song list.
        /// </summary>
        public static string SongList_Title {
            get {
                return ResourceManager.GetString("SongList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text is empty..
        /// </summary>
        public static string SongTextPresentation_EmptyText {
            get {
                return ResourceManager.GetString("SongTextPresentation_EmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account details:.
        /// </summary>
        public static string SupportMe_AccountDetails {
            get {
                return ResourceManager.GetString("SupportMe_AccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krzysztof Rutana.
        /// </summary>
        public static string SupportMe_AccountName {
            get {
                return ResourceManager.GetString("SupportMe_AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name:.
        /// </summary>
        public static string SupportMe_AccountNameLabel {
            get {
                return ResourceManager.GetString("SupportMe_AccountNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN:.
        /// </summary>
        public static string SupportMe_AccountNumber {
            get {
                return ResourceManager.GetString("SupportMe_AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIC/SWIFT:.
        /// </summary>
        public static string SupportMe_BicSwift {
            get {
                return ResourceManager.GetString("SupportMe_BicSwift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PKOPPLPW.
        /// </summary>
        public static string SupportMe_BicSwift_number {
            get {
                return ResourceManager.GetString("SupportMe_BicSwift_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any financial aid is also appreciated! .
        /// </summary>
        public static string SupportMe_Donate {
            get {
                return ResourceManager.GetString("SupportMe_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PL27 1240 5110 1111 0010 5758 5342.
        /// </summary>
        public static string SupportMe_IBAN {
            get {
                return ResourceManager.GetString("SupportMe_IBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please rate in the Google Store:.
        /// </summary>
        public static string SupportMe_Rate {
            get {
                return ResourceManager.GetString("SupportMe_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open on the Play Store.
        /// </summary>
        public static string SupportMe_RateButtonText {
            get {
                return ResourceManager.GetString("SupportMe_RateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support my work!.
        /// </summary>
        public static string SupportMe_SupportMyWork {
            get {
                return ResourceManager.GetString("SupportMe_SupportMyWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks!.
        /// </summary>
        public static string SupportMe_Thanks {
            get {
                return ResourceManager.GetString("SupportMe_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support my work.
        /// </summary>
        public static string SupportMe_Title {
            get {
                return ResourceManager.GetString("SupportMe_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you like the app?.
        /// </summary>
        public static string SupportMe_YouLikeApplication {
            get {
                return ResourceManager.GetString("SupportMe_YouLikeApplication", resourceCulture);
            }
        }
    }
}
