//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Show_song_text.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Show_song_text.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add selected.
        /// </summary>
        public static string AddSongToPlaylist_AddSelected {
            get {
                return ResourceManager.GetString("AddSongToPlaylist_AddSelected", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Choose songs.
        /// </summary>
        public static string AddSongToPlaylist_Title {
            get {
                return ResourceManager.GetString("AddSongToPlaylist_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You are sure you want to delete.
        /// </summary>
        public static string AlertDialog_AreYouSureToDelete {
            get {
                return ResourceManager.GetString("AlertDialog_AreYouSureToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cancel.
        /// </summary>
        public static string AlertDialog_Cancel {
            get {
                return ResourceManager.GetString("AlertDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Check the name again and try again..
        /// </summary>
        public static string AlertDialog_CheckNameAndTryAgain {
            get {
                return ResourceManager.GetString("AlertDialog_CheckNameAndTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Please complete at least one field (author or title)..
        /// </summary>
        public static string AlertDialog_CompleteAtLeastOneField {
            get {
                return ResourceManager.GetString("AlertDialog_CompleteAtLeastOneField", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Could not find artist&apos;s songs:.
        /// </summary>
        public static string AlertDialog_CouldNotFindArtistsSongs {
            get {
                return ResourceManager.GetString("AlertDialog_CouldNotFindArtistsSongs", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu We couldn&apos;t find matching artists.
        /// </summary>
        public static string AlertDialog_CouldntFindMachingArtists {
            get {
                return ResourceManager.GetString("AlertDialog_CouldntFindMachingArtists", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enter a name..
        /// </summary>
        public static string AlertDialog_EnterName {
            get {
                return ResourceManager.GetString("AlertDialog_EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enter title and author..
        /// </summary>
        public static string AlertDialog_EnterNameAndTitle {
            get {
                return ResourceManager.GetString("AlertDialog_EnterNameAndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Error.
        /// </summary>
        public static string AlertDialog_Error {
            get {
                return ResourceManager.GetString("AlertDialog_Error", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You are trying to move two or more songs, please move one at a time!.
        /// </summary>
        public static string AlertDialog_MoveMoreThanOneSong {
            get {
                return ResourceManager.GetString("AlertDialog_MoveMoreThanOneSong", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Playlist name cannot be empty!.
        /// </summary>
        public static string AlertDialog_NameCannotBeEmpty {
            get {
                return ResourceManager.GetString("AlertDialog_NameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No.
        /// </summary>
        public static string AlertDialog_No {
            get {
                return ResourceManager.GetString("AlertDialog_No", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu OK.
        /// </summary>
        public static string AlertDialog_OK {
            get {
                return ResourceManager.GetString("AlertDialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Playlist created!.
        /// </summary>
        public static string AlertDialog_PlaylistCreated {
            get {
                return ResourceManager.GetString("AlertDialog_PlaylistCreated", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search problem!.
        /// </summary>
        public static string AlertDialog_SearchProblem {
            get {
                return ResourceManager.GetString("AlertDialog_SearchProblem", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Please select artist and track manually..
        /// </summary>
        public static string AlertDialog_SelectArtistAndTrackManually {
            get {
                return ResourceManager.GetString("AlertDialog_SelectArtistAndTrackManually", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Success!.
        /// </summary>
        public static string AlertDialog_Success {
            get {
                return ResourceManager.GetString("AlertDialog_Success", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Text not found!.
        /// </summary>
        public static string AlertDialog_TextNotFound {
            get {
                return ResourceManager.GetString("AlertDialog_TextNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Could not find track for:.
        /// </summary>
        public static string AlertDialog_TextNotFoundFor {
            get {
                return ResourceManager.GetString("AlertDialog_TextNotFoundFor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Too many matching results, please refine your search!.
        /// </summary>
        public static string AlertDialog_ToManyMachingResults {
            get {
                return ResourceManager.GetString("AlertDialog_ToManyMachingResults", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Warning.
        /// </summary>
        public static string AlertDialog_Warning {
            get {
                return ResourceManager.GetString("AlertDialog_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Yes.
        /// </summary>
        public static string AlertDialog_Yes {
            get {
                return ResourceManager.GetString("AlertDialog_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Connection settings.
        /// </summary>
        public static string ConnectionSettings_Title {
            get {
                return ResourceManager.GetString("ConnectionSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Connect.
        /// </summary>
        public static string ConnectionSettingsClient_Connect {
            get {
                return ResourceManager.GetString("ConnectionSettingsClient_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Connected to the server.
        /// </summary>
        public static string ConnectionSettingsClient_ConnectedToServer {
            get {
                return ResourceManager.GetString("ConnectionSettingsClient_ConnectedToServer", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Disconnect the connection.
        /// </summary>
        public static string ConnectionSettingsClient_DisconnectConnection {
            get {
                return ResourceManager.GetString("ConnectionSettingsClient_DisconnectConnection", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu IP:.
        /// </summary>
        public static string ConnectionSettingsClient_IP {
            get {
                return ResourceManager.GetString("ConnectionSettingsClient_IP", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu enter the server&apos;s IP.
        /// </summary>
        public static string ConnectionSettingsClient_IPPlaceholder {
            get {
                return ResourceManager.GetString("ConnectionSettingsClient_IPPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Port:.
        /// </summary>
        public static string ConnectionSettingsClient_Port {
            get {
                return ResourceManager.GetString("ConnectionSettingsClient_Port", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu enter the port number.
        /// </summary>
        public static string ConnectionSettingsClient_PortPlaceholder {
            get {
                return ResourceManager.GetString("ConnectionSettingsClient_PortPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Run presentations.
        /// </summary>
        public static string ConnectionSettingsClient_RunPresentations {
            get {
                return ResourceManager.GetString("ConnectionSettingsClient_RunPresentations", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Client.
        /// </summary>
        public static string ConnectionSettingsHeaders_Client {
            get {
                return ResourceManager.GetString("ConnectionSettingsHeaders_Client", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Server.
        /// </summary>
        public static string ConnectionSettingsHeaders_Server {
            get {
                return ResourceManager.GetString("ConnectionSettingsHeaders_Server", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Connected devices: .
        /// </summary>
        public static string ConnectionSettingsServer_ComnnectedDevices {
            get {
                return ResourceManager.GetString("ConnectionSettingsServer_ComnnectedDevices", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu IP: .
        /// </summary>
        public static string ConnectionSettingsServer_IP {
            get {
                return ResourceManager.GetString("ConnectionSettingsServer_IP", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Port: .
        /// </summary>
        public static string ConnectionSettingsServer_Port {
            get {
                return ResourceManager.GetString("ConnectionSettingsServer_Port", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Server is running.
        /// </summary>
        public static string ConnectionSettingsServer_ServerRunning {
            get {
                return ResourceManager.GetString("ConnectionSettingsServer_ServerRunning", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Start the server.
        /// </summary>
        public static string ConnectionSettingsServer_StartServer {
            get {
                return ResourceManager.GetString("ConnectionSettingsServer_StartServer", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Stop the server.
        /// </summary>
        public static string ConnectionSettingsServer_StopServer {
            get {
                return ResourceManager.GetString("ConnectionSettingsServer_StopServer", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Empty fields.
        /// </summary>
        public static string ConnectionSettingsVM_EmptyField {
            get {
                return ResourceManager.GetString("ConnectionSettingsVM_EmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Please enter the port number.
        /// </summary>
        public static string ConnectionSettingsVM_PortNumber {
            get {
                return ResourceManager.GetString("ConnectionSettingsVM_PortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enter a playlist name: .
        /// </summary>
        public static string DisplayEntry_EnterPlaylistName {
            get {
                return ResourceManager.GetString("DisplayEntry_EnterPlaylistName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Choose an artist:.
        /// </summary>
        public static string DisplayPositionToChoose_ChooseArtist {
            get {
                return ResourceManager.GetString("DisplayPositionToChoose_ChooseArtist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Choose a song:.
        /// </summary>
        public static string DisplayPositionToChoose_ChooseSong {
            get {
                return ResourceManager.GetString("DisplayPositionToChoose_ChooseSong", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Singer&apos;s assistant.
        /// </summary>
        public static string MainPage_ApplicationName {
            get {
                return ResourceManager.GetString("MainPage_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu by Krzysztof Rutana.
        /// </summary>
        public static string MainPage_Author {
            get {
                return ResourceManager.GetString("MainPage_Author", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name:.
        /// </summary>
        public static string PlaylistDetail_Name {
            get {
                return ResourceManager.GetString("PlaylistDetail_Name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Songs:.
        /// </summary>
        public static string PlaylistDetail_Songs {
            get {
                return ResourceManager.GetString("PlaylistDetail_Songs", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Playlist details.
        /// </summary>
        public static string PlaylistDetail_Title {
            get {
                return ResourceManager.GetString("PlaylistDetail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Playlists.
        /// </summary>
        public static string PlaylistList_Title {
            get {
                return ResourceManager.GetString("PlaylistList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Font size:.
        /// </summary>
        public static string Settings_FontSize {
            get {
                return ResourceManager.GetString("Settings_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Language:.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select language:.
        /// </summary>
        public static string Settings_SelectLanguage {
            get {
                return ResourceManager.GetString("Settings_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add song.
        /// </summary>
        public static string SongAddAndDetail_AddSong {
            get {
                return ResourceManager.GetString("SongAddAndDetail_AddSong", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Author:.
        /// </summary>
        public static string SongAddAndDetail_Author {
            get {
                return ResourceManager.GetString("SongAddAndDetail_Author", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Playlists:.
        /// </summary>
        public static string SongAddAndDetail_Playlists {
            get {
                return ResourceManager.GetString("SongAddAndDetail_Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Song details.
        /// </summary>
        public static string SongAddAndDetail_SongDetail {
            get {
                return ResourceManager.GetString("SongAddAndDetail_SongDetail", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Text:.
        /// </summary>
        public static string SongAddAndDetail_Text {
            get {
                return ResourceManager.GetString("SongAddAndDetail_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Title:.
        /// </summary>
        public static string SongAddAndDetail_TitleName {
            get {
                return ResourceManager.GetString("SongAddAndDetail_TitleName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Create a playlist.
        /// </summary>
        public static string SongList_CreatePlaylist {
            get {
                return ResourceManager.GetString("SongList_CreatePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Song list.
        /// </summary>
        public static string SongList_Title {
            get {
                return ResourceManager.GetString("SongList_Title", resourceCulture);
            }
        }
    }
}
